---
# This playbook deploys the whole application stack in this site.
- name: Trigguer list of roles sent from Service Dialog using extra_var roles
  hosts: all
  connection: local
  environment:
    ansible_host_key_checking: false
  remote_user: root
  pre_tasks:
    - name: logging manageiq object
      debug: var=manageiq
      when: manageiq is defined
    - name: Logging cfmeroles
      debug: var=rolescfme

  roles:
    - { role: aip-container-services, when: '"aip-container-services" in rolescfme.split(",")' }
    - { role: aip-container-services, when: '"aip-container-service" in rolescfme.split(",")' }
    - { role: icd17, when: '"icd17" in rolescfme.split(",")' }
    - { role: apache, when: '"apache" in rolescfme.split(",")' }
    - { role: mysql, when: '"mysql" in rolescfme.split(",")' }
    - { role: php, when: '"php" in rolescfme.split(",")' }
    - { role: tomcat, when: '"tomcat" in rolescfme.split(",")' }
    - { role: managed, when: '"managed" in rolescfme.split(",")' }
    - { role: unmanaged, when: '"unmanaged" in rolescfme.split(",")' }
